# Generated by Django 5.2.8 on 2025-11-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabelStudioConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "labelstudio_url",
                    models.URLField(help_text="Label Studio instance URL"),
                ),
                (
                    "api_token",
                    models.CharField(
                        help_text="API token for Label Studio", max_length=255
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the connection has been verified",
                    ),
                ),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LabelStudioProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("labelstudio_project_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "label_config",
                    models.JSONField(
                        blank=True,
                        help_text="Label Studio labeling configuration",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether tasks from this project should be available to annotators",
                    ),
                ),
                ("total_tasks", models.IntegerField(default=0)),
                ("completed_tasks", models.IntegerField(default=0)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_enabled",
                    models.BooleanField(
                        default=True, help_text="Auto-sync tasks from Label Studio"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
