# Generated by Django 5.2.8 on 2025-11-07 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("integration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="labelstudioconnection",
            name="researcher",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labelstudio_connection",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="labelstudioproject",
            name="researcher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labelstudio_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="labelstudioconnection",
            index=models.Index(
                fields=["researcher"], name="integration_researc_df2e93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labelstudioproject",
            index=models.Index(
                fields=["labelstudio_project_id"], name="integration_labelst_3a8f3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labelstudioproject",
            index=models.Index(
                fields=["researcher", "is_active"],
                name="integration_researc_711140_idx",
            ),
        ),
    ]
