# Generated by Django 5.2.8 on 2025-11-07 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskassignment",
            name="annotator",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "annotator"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="tasks.task",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="tasks_task_status_4a0a95_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "status"], name="tasks_task_project_b78682_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["labelstudio_task_id"], name="tasks_task_labelst_ab5d63_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("project", "labelstudio_task_id")},
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(
                fields=["annotator", "status"], name="tasks_taska_annotat_aa1889_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(
                fields=["task", "status"], name="tasks_taska_task_id_d49859_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(fields=["status"], name="tasks_taska_status_6a8bf4_idx"),
        ),
    ]
