# Generated by Django migrations
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('auth.login', 'User Login'), ('auth.logout', 'User Logout'), ('auth.register', 'User Registration'), ('auth.password_change', 'Password Change'), ('task.create', 'Task Created'), ('task.claim', 'Task Claimed'), ('task.submit', 'Task Submitted'), ('task.approve', 'Task Approved'), ('task.reject', 'Task Rejected'), ('payment.initiated', 'Payment Initiated'), ('payment.completed', 'Payment Completed'), ('payment.failed', 'Payment Failed'), ('payment.refund', 'Payment Refunded'), ('wallet.connected', 'Wallet Connected'), ('wallet.updated', 'Wallet Updated'), ('wallet.disconnected', 'Wallet Disconnected'), ('admin.user_update', 'Admin User Update'), ('admin.task_override', 'Admin Task Override'), ('security.suspicious_activity', 'Suspicious Activity'), ('security.rate_limit', 'Rate Limit Exceeded')], db_index=True, help_text='Type of action performed', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action occurred')),
                ('resource_type', models.CharField(blank=True, db_index=True, help_text="Type of resource affected (e.g., 'task', 'payment', 'user')", max_length=50)),
                ('resource_id', models.CharField(blank=True, db_index=True, help_text='ID of the affected resource', max_length=100)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action (payment amounts, task IDs, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('success', models.BooleanField(default=True, help_text='Whether the action succeeded')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'permissions': [('view_audit_logs', 'Can view audit logs')],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique transaction identifier', max_length=100, unique=True)),
                ('amount_usdc', models.DecimalField(decimal_places=6, help_text='Amount in USDC', max_digits=18)),
                ('blockchain_network', models.CharField(default='base', help_text='Blockchain network (base, ethereum, etc.)', max_length=20)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash (0x...)', max_length=66, null=True, unique=True)),
                ('from_address', models.CharField(help_text='Platform wallet address (sender)', max_length=42)),
                ('to_address', models.CharField(help_text='Annotator wallet address (recipient)', max_length=42)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('gas_used', models.DecimalField(blank=True, decimal_places=6, help_text='Gas used for transaction', max_digits=18, null=True)),
                ('gas_price_gwei', models.DecimalField(blank=True, decimal_places=6, help_text='Gas price in Gwei', max_digits=18, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if transaction failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction metadata')),
                ('assignment', models.ForeignKey(help_text='Task assignment this payment is for', on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='tasks.taskassignment')),
                ('recipient', models.ForeignKey(help_text='User receiving the payment', on_delete=django.db.models.deletion.PROTECT, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='tasks_audit_timesta_f6d7a2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='tasks_audit_user_id_4a1c27_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', '-timestamp'], name='tasks_audit_action__3f5d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='tasks_audit_resourc_8e2b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['-created_at'], name='tasks_payme_created_9a2c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['recipient', '-created_at'], name='tasks_payme_recipie_1d4e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', '-created_at'], name='tasks_payme_status_7b6c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_hash'], name='tasks_payme_transac_2a3b4c_idx'),
        ),
    ]
