from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """
    Custom user model for Viberate platform.
    Supports both researchers (from Label Studio) and annotators (Viberate network).
    """
    USER_TYPE_CHOICES = (
        ('researcher', 'Researcher'),
        ('annotator', 'Annotator'),
    )

    user_type = models.CharField(
        max_length=20,
        choices=USER_TYPE_CHOICES,
        default='annotator'
    )

    # Label Studio integration fields
    labelstudio_user_id = models.IntegerField(
        null=True,
        blank=True,
        unique=True,
        help_text="User ID from Label Studio"
    )
    labelstudio_api_token = models.CharField(
        max_length=255,
        blank=True,
        help_text="API token for this user's Label Studio account"
    )

    # GitHub OAuth fields
    github_id = models.BigIntegerField(
        null=True,
        blank=True,
        unique=True,
        help_text="GitHub user ID"
    )
    github_username = models.CharField(
        max_length=255,
        blank=True,
        help_text="GitHub username"
    )

    # Annotator fields
    skills = models.JSONField(
        default=list,
        blank=True,
        help_text="Skills/specializations for annotators"
    )
    rating = models.FloatField(
        default=0.0,
        help_text="Average rating based on completed tasks"
    )
    tasks_completed = models.IntegerField(
        default=0,
        help_text="Total number of tasks completed"
    )

    # Crypto wallet fields (Base network)
    base_wallet_address = models.CharField(
        max_length=42,
        blank=True,
        help_text="Base network wallet address (0x...)"
    )
    wallet_data = models.TextField(
        blank=True,
        help_text="Encrypted wallet data from Coinbase CDP"
    )
    wallet_id = models.CharField(
        max_length=255,
        blank=True,
        help_text="Coinbase CDP wallet ID"
    )
    usdc_balance = models.DecimalField(
        max_digits=18,
        decimal_places=6,
        default=0,
        help_text="USDC balance on Base network"
    )

    # Profile fields
    bio = models.TextField(blank=True)
    avatar_url = models.URLField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user_type']),
            models.Index(fields=['labelstudio_user_id']),
            models.Index(fields=['github_id']),
        ]

    def __str__(self):
        return f"{self.username} ({self.user_type})"

    def is_researcher(self):
        return self.user_type == 'researcher'

    def is_annotator(self):
        return self.user_type == 'annotator'


class SkillProfile(models.Model):
    """
    GitHub-based skill profile for developers.
    Generated by analyzing their open source contributions.
    """
    TIER_CHOICES = (
        (1, 'Tier 1 - Expert'),
        (2, 'Tier 2 - Proficient'),
        (3, 'Tier 3 - Developing'),
    )

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='skill_profile'
    )

    # Top languages with scores (JSON array of {language, score, evidence_summary})
    top_languages = models.JSONField(
        default=list,
        help_text="Top programming languages with weighted scores"
    )

    # Domain tags (JSON array of strings)
    domain_tags = models.JSONField(
        default=list,
        help_text="Inferred domains like 'machine-learning', 'web-backend', etc."
    )

    # Overall credibility tier (1-3)
    credibility_tier = models.IntegerField(
        choices=TIER_CHOICES,
        default=3,
        help_text="Overall skill tier based on weighted score"
    )

    # Total weighted score across all languages/domains
    total_score = models.FloatField(
        default=0.0,
        help_text="Composite score from GitHub analysis"
    )

    # Collaboration signal (0.0-1.0, ratio of external vs solo work)
    collaboration_ratio = models.FloatField(
        default=0.0,
        help_text="Ratio of external contributions to solo work"
    )

    # Notable contributions (JSON array of top 3-5 PRs with details)
    notable_contributions = models.JSONField(
        default=list,
        help_text="Top contributions for human review"
    )

    # Raw GitHub data cache (for debugging/re-scoring without re-fetching)
    github_data_cache = models.JSONField(
        default=dict,
        blank=True,
        help_text="Cached GitHub API response data"
    )

    # Metadata
    last_analyzed = models.DateTimeField(
        auto_now=True,
        help_text="Last time profile was analyzed"
    )
    analysis_version = models.CharField(
        max_length=20,
        default='1.0',
        help_text="Version of scoring algorithm used"
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-total_score']
        indexes = [
            models.Index(fields=['credibility_tier']),
            models.Index(fields=['total_score']),
        ]

    def __str__(self):
        return f"Skill Profile for {self.user.username} (Tier {self.credibility_tier})"

    def get_top_language(self):
        """Get the highest-scored language"""
        if self.top_languages:
            return self.top_languages[0].get('language', 'Unknown')
        return 'Unknown'
